name: Emscripten build and test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - new-emscripten-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and test with Emscripten
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pyodide-build
        run: python3 -m pip install pyodide-build==0.28.0 pydantic
      - name: Determine EMSDK version
        id: compute-emsdk-version
        run: |
          # Prepare xbuild environment (side-effect)
          pyodide config list
          # Save EMSDK version
          EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
          echo "emsdk-version=$EMSCRIPTEN_VERSION" >> $GITHUB_OUTPUT
      - name: Install EMSDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ steps.compute-emsdk-version.outputs.emsdk-version }}
      - name: Build
        run: pyodide build
      - name: Set up Pyodide virtual environment
        run: |
          pyodide venv .venv-pyodide
          source .venv-pyodide/bin/activate
          python -m pip install pytest pytest-timeout awkward-cpp awkward scikit-hep-testdata boost-histogram
          python -m pip install .[test-wasm]
          python -c "import sys; print(sys.platform)"
      - name: Test
        run: |
          source .venv-pyodide/bin/activate
          python -m pytest -p no:cacheprovider -vv tests --reruns 3 --reruns-delay 30 --only-rerun "(?i)http|timeout|connection"
